language: generic
sudo: required

services:
  - docker

install:
  - HTTP_SERVER_ADDR=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
  - docker network create easyminer
  - docker pull mariadb:10
  - docker run --name easyminer-mysql -e MYSQL_ROOT_PASSWORD=root --network easyminer -d mariadb:10
  - docker pull kizi/easyminer-frontend:v2.4
  - docker run -d -p 8894:80 --name easyminer-frontend -e HTTP_SERVER_NAME="$HTTP_SERVER_ADDR:8894" --network easyminer kizi/easyminer-frontend:v2.4
  - docker pull kizi/easyminer-backend:v2.4
  - docker run -d -p 8893:8893 -p 8891:8891 -p 8892:8892 --name easyminer-backend -e EM_USER_ENDPOINT=http://easyminer-frontend/easyminercenter --network easyminer kizi/easyminer-backend:v2.4
  - docker pull kizi/easyminer-scorer:v2.4
  - docker run -d -p 8080:8080 --name easyminer-scorer --network easyminer kizi/easyminer-scorer:v2.4
  - docker pull kizi/easyminer-evaluation:latest

before_script:
  - sleep 15

script:
  - docker run -it --network easyminer kizi/easyminer-evaluation python ./easyminercenter/auto/short_test.py --api_url=http://easyminer-frontend/easyminercenter/api